# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hello(object):
    def setupUi(self, Hello):
        Hello.setObjectName("Hello")
        Hello.resize(332, 419)
        self.label = QtWidgets.QLabel(Hello)
        self.label.setGeometry(QtCore.QRect(20, 30, 311, 81))
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Hello)
        self.pushButton.setGeometry(QtCore.QRect(240, 380, 91, 34))
        self.pushButton.setObjectName("pushButton")
        self.Pname = QtWidgets.QLineEdit(Hello)
        self.Pname.setGeometry(QtCore.QRect(10, 220, 311, 32))
        self.Pname.setObjectName("Pname")
        self.lineEdit_1 = QtWidgets.QLineEdit(Hello)
        self.lineEdit_1.setGeometry(QtCore.QRect(10, 180, 311, 32))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit = QtWidgets.QLineEdit(Hello)
        self.lineEdit.setGeometry(QtCore.QRect(10, 140, 311, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.Cmd = QtWidgets.QLineEdit(Hello)
        self.Cmd.setGeometry(QtCore.QRect(10, 260, 311, 32))
        self.Cmd.setObjectName("Cmd")
        self.pushButton_2 = QtWidgets.QPushButton(Hello)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 380, 221, 34))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Hello)
        QtCore.QMetaObject.connectSlotsByName(Hello)

    def retranslateUi(self, Hello):
        _translate = QtCore.QCoreApplication.translate
        Hello.setWindowTitle(_translate("Hello", "Dialog"))
        self.label.setText(_translate("Hello", "Введите адрес сервера, хост. имя пользователя и команду для запуска вашего программируемого бота"))
        self.pushButton.setText(_translate("Hello", "Продолжить"))
        self.pushButton_2.setText(_translate("Hello", "Подключить в режиме просмотра"))
