# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminPage(object):
    def setupUi(self, AdminPage):
        AdminPage.setObjectName("AdminPage")
        AdminPage.resize(336, 432)
        self.label = QtWidgets.QLabel(AdminPage)
        self.label.setGeometry(QtCore.QRect(20, 10, 301, 141))
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(AdminPage)
        self.pushButton.setGeometry(QtCore.QRect(240, 390, 88, 34))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(AdminPage)
        self.lineEdit.setGeometry(QtCore.QRect(10, 120, 311, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_1 = QtWidgets.QLineEdit(AdminPage)
        self.lineEdit_1.setGeometry(QtCore.QRect(10, 160, 311, 32))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.Cmd = QtWidgets.QLineEdit(AdminPage)
        self.Cmd.setGeometry(QtCore.QRect(10, 200, 311, 32))
        self.Cmd.setObjectName("Cmd")
        self.Cmd_2 = QtWidgets.QLineEdit(AdminPage)
        self.Cmd_2.setGeometry(QtCore.QRect(10, 240, 311, 32))
        self.Cmd_2.setObjectName("Cmd_2")
        self.Cmd_3 = QtWidgets.QLineEdit(AdminPage)
        self.Cmd_3.setGeometry(QtCore.QRect(10, 280, 311, 32))
        self.Cmd_3.setObjectName("Cmd_3")
        self.Cmd_4 = QtWidgets.QLineEdit(AdminPage)
        self.Cmd_4.setGeometry(QtCore.QRect(10, 320, 311, 32))
        self.Cmd_4.setObjectName("Cmd_4")

        self.retranslateUi(AdminPage)
        QtCore.QMetaObject.connectSlotsByName(AdminPage)

    def retranslateUi(self, AdminPage):
        _translate = QtCore.QCoreApplication.translate
        AdminPage.setWindowTitle(_translate("AdminPage", "Dialog"))
        self.label.setText(_translate("AdminPage", "Вы были назначены администратором, введите параметры игры: высоту и ширину поля, количество игроков, таймаут, количество ходов и имя комнаты"))
        self.pushButton.setText(_translate("AdminPage", "Ок"))
